#set($dollar = '$')
# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
    
# Spring Boot
spring:

# Camel Spring Boot
camel:
  springboot:
    name: __CAMEL_SPRINGBOOT_NAME__

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel: DEBUG
    ${package}: INFO

# Application API
api:
  base-path: /camel
  swagger:
    base-path: ${dollar}{cxf.path}/${dollar}{api.base-path}
    license: __API_LICENSE__
    license-url: __API_LICENSE_URL__
    title: __API_TITLE__
    terms-of-service-url: __API_TERMS_OF_SERVICE_URL__
    version: __API_VERSION__
    description: __API_DESCRIPTION__
    contact: __API_CONTACT__
  cors:
    allowCredentials: true
    allowHeaders:
    allowOrigins:
    blockCorsIfUnauthorized: false
    defaultOptionsMethodsHandlePreflight: true
    exposeHeaders:
    findResourceMethod: true
    maxAge: 2147483647
    preflightErrorStatus: 200